//Variables
// const productName = "iPhone 16"

// let stock = 20;

// stock = 35;

// console.log(productName, " remaining ", stock)


//Data Types
// const customerName = "Roland"
// let quantity = 5
// const isPaid = true
// let discountCode = null
// let deliveryDate;

// console.log(typeof customerName)
// console.log(typeof quantity)
// console.log(typeof isPaid)
// console.log(typeof discountCode)
// console.log(typeof deliveryDate)

// Functions
// function multiply(a, b) {
//     return a * b
// }

// const result = multiply(6, 7)

// console.log(result)


// Arrays
const products = [
    "iPhone 16",
    "HP Laptop",
    "Samsung Tablet"
]

console.log(products)
products.push("Airpods Pro")
console.log(products.length)
console.log(products.includes("HP Laptop"))
